### ISSUE TITLE
front_right_door and front_left_door are switched

### ISSUE THREAD

**Issue by BunpGhost** [buxtronix/phev2mqtt#14]
From my testing, when I open the front right door, the left door icon turns yellow and vice-versa. 
So I believer that the binary_sensor.phev_front_right_door is switched with the binary_sensor.phev_front_left_door

**Comment by martingjohn** [comment]
I've not checked mine but out of interest do you have a right or left hand drive car? I know the car switches some things over (like which speaker the handsfree calls come out of) depending on how it's set up.
I presume the back doors do the same?

**Comment by BunpGhost** [comment]
I have a left hand drive car.
It is an EU model.
The back doors are correct :) So the I believe it is only the binary_sensor.phev_front_right_door that is switched with the binary_sensor.phev_front_left_door.

Can you check yours?

**Comment by martingjohn** [comment]
How weird.
For some reason my setup's stopped working at the moment but I'll retry when/if I get it back working again :(

**Comment by martingjohn** [comment]
Mine seem to match the doors, I'm in the UK with a UK right hand drive version '18 model.

**Comment by buxtronix** [comment]
I've resolved this by using the new topics `phev/door/front_passenger` and `phev/door/driver`.

The `phev/door/front_left` and `phev/door/front_right` MQTT topics are now deprecated - data is still published to them for now but their use is discouraged and they are no longer advertised in the HA MQTT discovery topic.

(FWIW, my car is also RHD so would match any UK models, but not EU/US)

**Comment by BunpGhost** [comment]
It is correct now. Just compiled the latest version.

Changed the frontend yaml to this:
`  
  - type: state-icon
    entity: binary_sensor.phev_driver_door
    icon: mdi:car-door
    style:
      top: 50%
      left: 7%
  - type: state-icon
    entity: binary_sensor.phev_front_passenger_door
    icon: mdi:car-door
    style:
      top: 50%
      left: 90%`
     
and the result:
![image](https://user-images.githubusercontent.com/25492163/168047487-9c46d77e-3cfb-4127-89dc-855fd953edb0.png)

I'm closing the issue. Thanks :)
