### ISSUE TITLE
sensor.phev_battery sometimes shows incorrect amount

### ISSUE THREAD

**Issue by martingjohn** [buxtronix/phev2mqtt#2]
Not narrowed down what's happening here but the sensor.phev_battery stops showing the correct value (currently on my car 94%), starts showing an incorrect value (possibly 100%-correct value) (currently on my car 5%), then back to the correct value.

Looking at the history from MQTT explorer (for phev/battery/level), it's around 5mins at right value, between 5-30s at incorrect value, then back again.

I'll see if I can set up some traces for more info.

**Comment by buxtronix** [comment]
I've seen this site regularly also. The incorrect value is being sent by the car, so not caused by a problem with this code.

I've also seen it in the official app also, briefly showing 5% until the car updates again.

I imagine it can only be solved by some sort of hysteresis code.

**Comment by martingjohn** [comment]
Ah, ok - yes, I've not reinstalled the official app since swiping the MAC address to use with this - that was going to be my first port of call.
In that case I'll just implement some code to hide those temporary blips from my Node Red notifications to remind me to charge/stop charging the car.
Thanks for the update

**Comment by nagisa** [comment]
Sorry to absolutely necro this, but one very curious thing I'm seeing on a MY19 is that before the battery level the vehicle always sends registers 0x0C and 0x0D with different values.

In my case `0c = 04 | 0d = 02 | 1d = 05000003` and `0c = 01 | 0d = 01 | 1d = 5e000003`.

I wonder if you can see the same?

At the same time a shot in the dark, but could this 5% be something like… headroom/capacity reservation? Adding the two numbers would almost get the 100%.
