### ISSUE TITLE
Unstable connection

### ISSUE THREAD

**Issue by martingjohn** [buxtronix/phev2mqtt#5]
Out of interest, what do you use to connect to the Outlander with?

I was becoming frustrated with my Raspberry Pi's seemingly flaky connection, so I bought a little Mikrotik router, set it all up to connect and route to the Outlander, which seemed to work fine (i.e. 100% ping success) until I start phev2mqtt up, where it then works for about a minute and then I lose connection to the Outlander. If I restart the Mikrotik wireless interface, it all comes back up again for another minute and the cycle repeats

```
root@pi4:~/phev# ./start.sh
INFO[0000] %PHEV_TCP_CONNECTED%
INFO[0066] Connection closed.
ERRO[0066] Connection closed.
ERRO[0066] %PHEV_TCP_WRITER_ERROR%: write tcp 192.168.100.90:38430->192.168.8.46:8080: use of closed network connection
ERRO[0067] dial tcp 192.168.8.46:8080: connect: connection refused
ERRO[0075] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0079] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0082] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0085] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0088] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0091] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0094] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0097] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0100] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0103] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0104] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0105] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0106] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0107] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0108] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0109] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0110] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0111] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0112] dial tcp 192.168.8.46:8080: connect: no route to host
ERRO[0113] dial tcp 192.168.8.46:8080: connect: no route to host
INFO[0114] %PHEV_TCP_CONNECTED%
INFO[0189] Connection closed.
```

Which all seems a little weird

Same thing happens when I do a netcat ```nc 192.168.8.46 8080```
Just wondered if you'd seen similar behaviour and if so if you had any hints?

**Comment by martingjohn** [comment]
Ah, it seems that if I let my Raspberry Pi use the default route to my firewall and have the static route there set to go to the Mikrotik router out to the Outlander then I get this weird behaviour. But if I set the route directly on my Raspberry Pi to go directly to the the Miktrotik router then it works fine.

If it's use to anyone, I'm using a MikroTik RouterBoard mAP lite (https://linitx.com/product/mikrotik-routerboard-map-lite/14639)
```
#Set wlan1 mac address to match that from my phone and created security profile and connect
/interface wireless 
set wlan1 mac-address=<xx:xx:xx:xx:xx:xx>
add authentication-types=wpa-psk,wpa2-psk \
    management-protection=allowed \
    mode=dynamic-keys name=Outlander \
    supplicant-identity=MikroTik \
    wpa-pre-shared-key=<secret-password> \
    wpa2-pre-shared-key=<secret-password>
set [ find default-name=wlan1 ] \
	band=2ghz-b/g/n \
	disabled=no \
	frequency=2422 \
	installation=indoor \
	security-profile=Outlander \
	mode=station \
	ssid=<outlander-ssid>

#Get IP addresses
/ip dhcp-client 
add dhcp-options=hostname,clientid \
    disabled=no \
    add-default-route=no \
    use-peer-dns=no \
    use-peer-ntp=no \
    interface=wlan1
add dhcp-options=hostname,clientid \
    disabled=no \
    interface=ether1

#Set NAT masquerade
/ip firewall nat
    add chain=srcnat action=masquerade out-interface=wlan1
```
Then on raspberry pi just set the route with (192.168.100.99 is the Mikrotik ether1 IP address)
```route add -net 192.168.8.0 netmask 255.255.255.0 gw 192.168.100.99 eth0```

**Comment by buxtronix** [comment]
I have a patch that allows running a script on too many connect failures. In my case restarting the RPi Wifi. I'll merge it here shortly.

**Comment by buxtronix** [comment]
Interestingly I also have a Mikrotik and got similar flaky behaviour. But now I have Pi Zero W close to the car and use the wifi restart feature which I've just merged. Seems pretty reliable now.

**Comment by martingjohn** [comment]
I think most of the problems I have are with the Mitsubishi Wi-Fi point. I often can't get it to connect and even when it does, I often have issues even pinging the car :(
