### ISSUE TITLE
Question on Go arch variant

### ISSUE THREAD

**Issue by DrOetkerNL** [buxtronix/phev2mqtt#8]
I have the following Raspberry PI:

https://www.sossolutions.nl/raspberry-pi-3-model-b-plus, 
which has the following proc: Broadcom BCM2837B0, Cortex-A-53, 64-bit SoC @ 1.4 GHz

Which Go Arch variant should I download? The ARMv6 or the ARM64? 

Thank you for your answer!

**Comment by martingjohn** [comment]
It'll depend on whether you installed a 64 or 32bit os. I installed 32bit (as 64bit was a bit experimental at the time, possibly still is) so `uname -m` comes back for me as `armv7l` which meant I used ARMv6 originally (before moving to Docker). If it says `aarch64` then you're running 64bit and probably could use either but I guess it would make most sense to use ARM64. (https://www.raspberrypi.org/forums/viewtopic.php?t=251721).
